# Generated by Django 2.2.16 on 2020-09-17 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_customtext_this_is_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='this_is_fk',
        ),
        migrations.AddField(
            model_name='customtext',
            name='this_is_fk_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_this_is_fk_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customtext',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
